name: MarkerSpawners
version: '${version}'
main: xyz.gerleig.markerspawners.MarkerSpawners
api-version: 1.18
authors: [ gerleig ]
description: Made to bridge vanilla spawners and mythicmobs, for a custom project.
depend: [ MythicMobs ]
permissions:
  markerspawners.break:
    description: "Ability to break markerspawners"
    default: op
